/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "llist.h"
#ifndef _KERNEL
#include <stdio.h>
#include <stdlib.h> /* getenv, exit */
#endif /* !_KERNEL */

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
print_list_1(argp, clnt)
	list *argp;
	CLIENT *clnt;
{
	static int clnt_res;

	(void) memset(&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, PRINT_LIST,
		(xdrproc_t)xdr_list, (caddr_t)argp,
		(xdrproc_t)xdr_int, (caddr_t)&clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
sum_list_1(argp, clnt)
	list *argp;
	CLIENT *clnt;
{
	static int clnt_res;

	(void) memset(&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, SUM_LIST,
		(xdrproc_t)xdr_list, (caddr_t)argp,
		(xdrproc_t)xdr_int, (caddr_t)&clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
