	
all:bub_int.java
	javac bub_int.java
	java bub_int
	java bub_double
	java bub_tem_int
	java bub_tem_double

temp:
	javac bub_abs_tem.java
	javac bub_tem_int.java
	java bub_tem_int

clean:
	rm -rf *.class
