/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "mount.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
mountproc_null_1(void *argp, void *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, MOUNTPROC_NULL,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
mountproc_mnt_1(dirpath *argp, fhstatus *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, MOUNTPROC_MNT,
		(xdrproc_t) xdr_dirpath, (caddr_t) argp,
		(xdrproc_t) xdr_fhstatus, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
mountproc_dump_1(void *argp, mountlist *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, MOUNTPROC_DUMP,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_mountlist, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
mountproc_umnt_1(dirpath *argp, void *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, MOUNTPROC_UMNT,
		(xdrproc_t) xdr_dirpath, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
mountproc_umntall_1(void *argp, void *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, MOUNTPROC_UMNTALL,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
mountproc_export_1(void *argp, exports *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, MOUNTPROC_EXPORT,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_exports, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
mountproc_exportall_1(void *argp, exports *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, MOUNTPROC_EXPORTALL,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_exports, (caddr_t) clnt_res,
		TIMEOUT));
}
